# Generated by Django 4.0.4 on 2022-07-15 13:16

from django.db import migrations, models
import stream.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y', validators=[stream.validators.file_size])),
            ],
        ),
    ]
